---
- name: Join to Kubernetes cluster
  shell: 
    cmd: kubeadm join --token {{ kubeadm_token }} --discovery-token-ca-cert-hash {{ kubeadm_sha_hash }} {{ master_ip }}:6443
    creates: /etc/kubernetes/kubelet.conf
  when: reset_cluster is succeeded
