---
- name: Initialize kubernetes-cluster
  shell: 
    cmd: "/usr/bin/kubeadm init"
    creates: /etc/kubernetes/admin.conf

- name: Create Kubernetes config directory
  file:
    path: "/home/{{ kubeadm.os_user.user }}/.kube/"
    owner: "{{ kubeadm.os_user.user }}"
    group: "{{ kubeadm.os_user.group }}"
    mode: '0755'
    state: directory

- name: Store admin.conf-file locally into files/kubeadm_admin.conf
  fetch: 
    src: "/etc/kubernetes/admin.conf"
    dest: "{{ role_path }}/files/kubeadm_admin.conf"
    flat: yes
