---
- name: "Copy yaml file"
  copy:
    src: "kubeadm/rbac-config.yml"
    dest: "/home/{{ kubeadm.os_user.user }}/rbac-config.yml"
    mode: 0644
  become: yes

- name: Apply Weave-Network
  shell: "export KUBECONFIG=/home/{{ kubeadm.os_user.user }}/.kube/admin.conf; kubectl apply -f https://cloud.weave.works/k8s/net?k8s-version=$(kubectl version | base64 | tr -d '\n')"
  become: yes

- name: "Apply Tiller"
  shell: "export KUBECONFIG=/home/{{ kubeadm.os_user.user }}/.kube/admin.conf; kubectl apply -f /home/{{ kubeadm.os_user.user }}/rbac-config.yml"
  become: yes

# kubectl apply -f "https://cloud.weave.works/k8s/net?k8s-version=$(kubectl version | base64 | tr -d '\n')"
# helm repo add stable https://kubernetes-charts.storage.googleapis.com/