---
- name: Create kubernetes-user
  include_tasks: kubeadm/kubeadm-create_user.yml
  when: 
    - ( k8s_node == "master" or k8s_node == "node" )
    - serveNet_ip is defined
    - kubernetes_engine == "kubeadm"