---
- name: Create kubernetes-user
  include_tasks: kubeadm/kubeadm-create_user.yml
  when: 
    - k8s_node is defined
    - serveNet_ip is defined
    - k8s_node in [ "master", "node" ]
    - kubernetes_engine == "kubeadm"

- name: Setup kubeadm-master
  include_tasks: kubeadm/kubeadm-master.yml
  when: 
    - k8s_node is defined
    - serveNet_ip is defined
    - k8s_node == "master"
    - kubernetes_engine == "kubeadm"

- name: Setup kubeadm-node
  include_tasks: kubeadm/kubeadm-node.yml
  when: 
    - k8s_node is defined
    - serveNet_ip is defined
    - k8s_node in [ "master", "node" ]
    - kubernetes_engine == "kubeadm"

- name: Setup kubernetes-user
  include_tasks: kubeadm/kubeadm-user_setup.yml
  when: 
    - k8s_node is defined
    - serveNet_ip is defined
    - k8s_node in [ "master", "node" ]
    - kubernetes_engine == "kubeadm"

- name: Default-Deployments
  include_tasks: kubeadm/kubeadm-postinstall.yml
  when: 
    - k8s_node is defined
    - serveNet_ip is defined
    - k8s_node == "master"
    - kubernetes_engine == "kubeadm"