---
- name: Downloading newest k3s binaries locally
  local_action: get_url url={{ item }} dest={{ role_path }}/files
  run_once: true
  with_items: 
    - https://github.com/rancher/k3s/releases/download/{{ k3s.version }}/k3s
    - https://github.com/rancher/k3s/releases/download/{{ k3s.version }}/k3s-arm64
    - https://github.com/rancher/k3s/releases/download/{{ k3s.version }}/k3s-armhf

- name: Delete k3s if already present
  file:
      path: /usr/local/bin/k3s
      state: absent

- name: Copy k3s binary x64
  copy:
      src: "{{ role_path }}/files/k3s"
      dest: /usr/local/bin/k3s
      owner: root
      group: root
      mode: 755
  when: 
    - ansible_facts.architecture == "x86_64"
    - k8s_node is defined

- name: Copy k3s binary arm64
  copy:
      src: "{{ role_path }}/files/k3s-arm64"
      dest: /usr/local/bin/k3s
      owner: root
      group: root
      mode: 755
  when:
    - ansible_facts.architecture is search("aarch64")
    # - ansible_facts.architecture is search("arm")
    # - ansible_facts.userspace_bits == "64"
    - k8s_node is defined

- name: Copy k3s binary armhf
  copy:
      src: "{{ role_path }}/files/k3s-armhf"
      dest: /usr/local/bin/k3s
      owner: root
      group: root
      mode: 755
  when: 
    - ansible_facts.architecture is search("arm")
    - ansible_facts.userspace_bits == "32"
    - k8s_node is defined    
