---
- name: Create k3s-users
  include_tasks: k3s/k3s-create_user.yml
  when: 
    - ( k8s_node == "master" or k8s_node == "node" )
    - serveNet_ip is defined
    - kubernetes_engine == "k3s"

- name: Download r3s-binary
  include_tasks: r3s/k3s-download.yml
  when: 
    - ( k8s_node == "master" or k8s_node == "node" )
    - kubernetes_engine == "k3s"
  loop_control:
      loop_var: host_item

- name: Setup r3s-master
  include_tasks: r3s/k3s-master.yml
  when: 
    - k8s_node == "master"
    - kubernetes_engine == "k3s"

- name: Setup r3s-node
  include_tasks: r3s/k3s-node.yml
  when: 
    - k8s_node == "node"
    - kubernetes_engine == "k3s"