---
- name: Set prereqs for kubernetes
  include_tasks: k3s-prereq.yml
  when: 
    - ( k8s_node == "master" or k8s_node == "node" )
    - kubernetes_engine == "k3s"

- name: Set prereqs for kubernetes
  include_tasks: k3s-download.yml
  when: 
    - ( k8s_node == "master" or k8s_node == "node" )
    - kubernetes_engine == "k3s"
  loop_control:
      loop_var: host_item

- name: Set prereqs for kubernetes
  include_tasks: k3s-raspbian.yml
  when: 
    - ( k8s_node == "master" or k8s_node == "node" )
    - kubernetes_engine == "k3s"

- name: Setup kubernetes master
  include_tasks: k3s-master.yml
  when: 
    - k8s_node == "master"
    - kubernetes_engine == "k3s"

- name: Setup kubernetes node
  include_tasks: k3s-node.yml
  when: 
    - k8s_node == "node"
    - kubernetes_engine == "k3s"