---
- name: Set Hostname
  hostname:
    name: "{{ inventory_hostname }}"

- name: Generiere /etc/hosts-file - default
  template:
    src: hostfile/hosts.j2
    dest: /etc/hosts
    owner: root
    group: root
    mode: '0644'
  when: 
    - serveNet_ip is not defined
    - build_full_hostsfile is not defined or not build_full_hostsfile
    - no_hostfile is defined and not no_hostfile

- name: Generiere /etc/hosts-file - all Ansible-hosts
  template:
    src: hostfile/hosts-all.j2
    dest: /etc/hosts
    owner: root
    group: root
    mode: '0644'
  when: 
    - serveNet_ip is not defined
    - build_full_hostsfile
    - no_hostfile is defined and not no_hostfile

- name: Generiere /etc/hosts-file - serveNet
  template:
    src: hostfile/hosts-serveNet.j2
    dest: /etc/hosts
    owner: root
    group: root
    mode: '0644'
  when: 
    - serveNet_ip is defined
    - no_hostfile is defined and not no_hostfile

- name: Generate locales
  locale_gen:
    name: "{{ item }}"
    state: present
  with_items:
    - de_AT.UTF-8
    - de_DE.UTF-8
    - en_GB.UTF-8
    - en_US.UTF-8

- name: Set default locale
  lineinfile:
    path: /etc/default/locale
    regexp: '^LANG='
    line: 'LANG=de_AT.UTF-8'

- name: Set timezone to Europe/Vienna
  timezone:
    name: Europe/Vienna

- name: Default-Services
  service:
    name: "{{ item }}"
    enabled: yes
    state: started
  with_items:
    - ssh

- name: Install Kernel-modules
  modprobe:
    name: 8021q
    state: present