---
- name: Generate locales
  locale_gen:
    name: "{{ item }}"
    state: present
  with_items:
    - de_AT.UTF-8
    - de_DE.UTF-8
    - en_GB.UTF-8
    - en_US.UTF-8

- name: Set default locale
  lineinfile:
    path: /etc/default/locale
    regexp: '^LANG='
    line: 'LANG=de_AT.UTF-8'

- name: Set timezone to Europe/Vienna
  timezone:
    name: Europe/Vienna

- name: Add repository for Raspian stretch
  apt_repository:
    repo: "{{ item }}"
    state: present
  with_items:
    - deb http://mirrordirector.raspbian.org/raspbian/ stable main contrib non-free rpi firmware
    - deb http://archive.raspberrypi.org/debian/ stretch main ui
  when: 
    - ansible_distribution == "Debian"
    - ansible_distribution_release == "stretch"
    - ansible_architecture == "armv6l"

- name: Install default Packages
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - vlan
    - debian-keyring
    - debian-archive-keyring
    - debian-ports-archive-keyring
    - git

- name: Default-Services
  service:
    name: "{{ item }}"
    enabled: yes
    state: started
  with_items:
    - ssh

- name: Install Kernel-modules
  modprobe:
    name: 8021q
    state: present

- hostname:
    name: "{{ ansible_hostname }}"