---
- name: Generate Directory Structure for Network-Mounts
  file:
    path: "{{ item.mountpoint }}"
    state: directory
    owner: root
    group: root
    mode: 0755
  when: do_mount_filesystems
  with_items:
    - "{{ mount_filesystems }}"

- name: Install Software packages for mount
  apt:
    name: [ cifs-utils, nfs-common ]
    state: present
    update_cache: no

- name: Mount remote-filesystem
  mount:
    path: "{{ item.mountpoint }}"
    src: "{{ item.remote }}"
    fstype: "{{ item.type }}"
    opts: "{{ item.options }}"
    state: mounted
  when: do_mount_filesystems
  ignore_errors: yes
  with_items:
    - "{{ mount_filesystems }}"