---
- name: Delete Cloud-Init Configuration
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - /etc/network/interfaces.d/50-cloud-init.cfg

- name: Generiere /etc/network/interfaces.d/30-ansible.cfg
  template:
    src: "network/30-ansible.cfg.j2"
    dest: "/etc/network/interfaces.d/30-ansible.cfg"
    owner: root
    group: root
    mode: '0644'

- name: Generiere /etc/dhcpcd.exit-hook
  template:
    src: "network/dhcpcd.exit-hook.j2"
    dest: "/etc/dhcpcd.exit-hook"
    owner: root
    group: root
    mode: '0744'
  when: serveNet_ip is defined

- name: Generiere /etc/network/interfaces.d/35-serveNet-ansible.cfg
  template:
    src: "network/35-serveNet-ansible.cfg.j2"
    dest: "/etc/network/interfaces.d/35-serveNet-ansible.cfg"
    owner: root
    group: root
    mode: '0644'
  when: serveNet_ip is defined

- name: Generiere /etc/wpa_supplicant/wpa_supplicant.conf
  template:
    src: "network/wpa_supplicant.conf.j2"
    dest: "/etc/wpa_supplicant/wpa_supplicant.conf"
    owner: root
    group: root
    mode: '0600'
  when: hardware["wireless_lan"] is defined

- name: Generiere /etc/avahi/services/sftp-ssh.services
  template:
    src: "avahi/ssh.services.j2"
    dest: "/etc/avahi/services/ssh.services"
    owner: root
    group: root
    mode: '0644'
  register: avahi_ssh

- name: Generiere /etc/avahi/services/sftp-ssh.services
  template:
    src: "avahi/sftp-ssh.services.j2"
    dest: "/etc/avahi/services/sftp-ssh.services"
    owner: root
    group: root
    mode: '0644'
  register: avahi_sftp

- name: Check if Avahi-Service exists 
  stat:
    path: "/etc/systemd/system/multi-user.target.wants/avahi-daemon.service"
  when: service_avahi

- name: Restart avahi-daemon when services changed
  systemd:
    name: avahi-daemon
    daemon_reload: yes
    state: restart
    enabled: yes
  when:
    - ( avahi_ssh.changed or avahi_sftp.changed )
    - service_avahi.stat.exists