---
- name: Upgrade Packages
  apt:
    upgrade: yes
    update_cache: yes
  when: do_software_upgrade

- name: Deinstall Packages
  apt:
    name: "{{ item }}"
    state: present
    update_cache: no
  with_items:
    - cloud-init