---
- name: Create defaut Groups
  group:
    name: "{{ item.name }}"
    gid: "{{ item.uid }}"
    state: present
  with_items:
    - "{{ admin_users }}"
    - { name: "sudo-nopwd", uid: "1199" }

- name: Set sudo-nopwd-settings in sudoers-file
  lineinfile:
    path: /etc/sudoers
    regexp: '^%sudo-nopwd '
    insertafter: '^%sudo'
    line: '%sudo-nopwd ALL=(ALL) NOPASSWD: ALL'
    validate: '/usr/sbin/visudo -cf %s'

- name: Create defaut User
  user:
    name: "{{ item.name }}"
    comment: "{{ item.full_name }}"
    group: "{{ item.name }}"
    groups: "{{ admin_groups }}"
    password: "{{ item.password }}"
    uid: "{{ item.uid }}"
    shell: "{{ item.shell }}"
    generate_ssh_key: yes
    ssh_key_bits: 2048
    ssh_key_file: .ssh/id_rsa
    state: present
  with_items:
    - "{{ admin_users }}"

- name: Remove default Users
  user:
    name: "{{ item }}"
    state: absent
  with_items:
    - pi
    - pirate

- name: Remove defaut Groups
  group:
    name: "{{ item }}"
    state: absent
  with_items:
    - pi
    - pirate

- name: Set SSH-Key for default Admin User
  authorized_key:
    user: "{{ item.user }}"
    key: "{{ item.key }}"
    state: present
  with_items:
    - "{{ ssh_keys }}"